// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rda-1Ka7HuB2Dh1J7YXDw8wpUYLwy_A',
    appId: '1:880175474616:web:8a8a426851991c192dd14d',
    messagingSenderId: '880175474616',
    projectId: 'mealmind-e00b5',
    authDomain: 'mealmind-e00b5.firebaseapp.com',
    storageBucket: 'mealmind-e00b5.firebasestorage.app',
    measurementId: 'G-KDTVWVS5P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjG3BPQ3gaIi4Mg_RB6pRy7Rvtx63e2ZQ',
    appId: '1:880175474616:android:7a0e733bd723cabd2dd14d',
    messagingSenderId: '880175474616',
    projectId: 'mealmind-e00b5',
    storageBucket: 'mealmind-e00b5.firebasestorage.app',
  );
}
